### PR TITLE
Adding Redwood City OWRS file for 07-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull please review
Could not find any info about landscape factor. 
http://www.redwoodcity.org/departments/public-works/water/rates/current-rates

**Comment by patwater** [comment]
@ArashSeif what do you need the landscape factor for? These don't appear to be budget based rates

**Comment by ArashSeif** [comment]
Irrigation rates are budget based. Assumed landscape factor is 0.7 but couldn't find anything on their website to confirm it.

**Comment by patwater** [comment]
Ah I see. @ArashSeif could you please try emailing the city? Note appears their water rates were last changed in 2014 so another option is to dig through old city council packets from then to find the prop 218 notice

For future records here is their 2018 sewer rates 218: http://www.redwoodcity.org/home/showdocument?id=13001

**Pull request merged**
