### PR TITLE
Adding Glendora  City Of OWRS file for 01-01-2018

### PR DESCRIPTION
**Pull request by christophertull**

### CODE REVIEW

**Comment by christophertull** [comment]
cant find info online, but doesn't seem right

**Comment by ArashSeif** [comment]
@christophertull @patwater called their utility billing department and they emailed the rates. I'm still very confused about the tiers. Please review 
glendora rates

**Comment by christophertull** [comment]
As best as I can tell, they have 4 different pricing zones (1,2,3,4+), these could be our `pressure_zone`s but it is unclear. Each of these zones has distinct volumetric pricing.

I think they have two tiers - the last two rows in the "Quantity Water Rates" table. I think the Purchase Water Rate, Energy Base, etc are just sub-charges that add up to the Quantity Rates in the bottom two rows.

I have no idea what their tier widths are though... Could be budget based? Maybe worth a follow-up email to their billing staff.

**Comment by patwater** [comment]
Yeah @ArashSeif feel free to cc Chris and I on a follow up email. This is a unique case

**Comment by patwater** [comment]
@ArashSeif did you email Glendora?

**Comment by ArashSeif** [comment]
@patwater Just emailed them. Waiting for their response.

**Comment by ArashSeif** [comment]
[Scanned from Glendora - Finance[1093].pdf](https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/files/1718078/Scanned.from.Glendora.-.Finance.1093.pdf)
Rates are updated. Tier breaks are under "bi-monthly baseline allocation" for each meter size and the prices are the bottom two rows in the "Quantity Water Rates" table. @christophertull @patwater please review.

**Comment by christophertull** [comment]
@ArashSeif Well done! This was a tricky one. I think the OWRS file makes more sense than their PDF (But I am probably biased :P )

**Comment by christophertull** [comment]
Looks like the baseline allocation is also bi-monthly, so I switched their billing frequency to bi-monthly

**Comment by christophertull** [comment]
Only tricky part remaining is what units they use. If we can't find anything then we can just assume CCF. 

Have you found anything here @ArashSeif or are we just assuming?

**Comment by ArashSeif** [comment]
@christophertull according to this video ccf is the right unit
http://www.cityofglendora.org/Home/Components/News/News/3526/23

**Pull request merged**
