### PR TITLE
Adding Suburban Water Systems OWRS file for 01-01-2017

### PR DESCRIPTION
**Pull request by patwater**

### CODE REVIEW

**Comment by patwater** [comment]
Pretty sure there are errors (tier prices are 0 / 20 same as tier starts) though can't (easily) find info online

**Comment by ArashSeif** [comment]
@patwater @christophertull 
Suburban Water System has two different service areas, Whittier/La Mirada and San Jose Hills. They are added separately, #226 and #227. I think we can replace this file with those two.
https://www.swwc.com/suburban/tariff/

**Comment by patwater** [comment]
Great sounds good. Just note please keep the final files in separate folders such as Suburban La Mirada/Whittier and Suburban San Jose Hills

CC @christophertull

**Comment by christophertull** [comment]
The other two are merged so closing this one.

**Pull request closed without merging**
