### PR TITLE
Adding Monterey Park  City Of LA OWRS file for 09-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull Please Review. 
https://www.montereypark.ca.gov/1171/Water-Rate-Schedule

**Comment by christophertull** [comment]
@ArashSeif can you please elaborate on logic for closing and deleting without merging first?

**Comment by ArashSeif** [comment]
@christophertull this was the file we discussed earlier today. I added the current rates through the survey first, then realized the name difference with another branch containing 2018 rates #134. The survey goes through but the rates won't be added to the branch when using the same name. 
Once #134 is merged I'll add 2017 rates again.

**Comment by christophertull** [comment]
Oh, I see. Yeah that works. thanks

**Pull request closed without merging**
