### PR TITLE
Adding Downey  City Of OWRS file for 01-01-2013

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull please review
Rates are current. Effective date could not be found and 01-01-2018 is assumed.
http://www.downeygis.org/waterrates/waterratesschedule2013.pdf
http://downeygis.org/ProposedWaterRatesV1/Proposed-Water-Rate-Calculations/Add-Proposed-Water-Rate-Calculations.aspx

**Comment by patwater** [comment]
Please change effective date to 1/1/2013 per rate schedule file name

**Comment by christophertull** [comment]
Note we will have to change the OWRS file name also. Looks like the PR title and the text of the OWRS file have already been changed.

**Comment by christophertull** [comment]
Ok I went ahead and renamed the file

**Comment by patwater** [comment]
Cool C are we good to merge then?

**Pull request merged**
