### PR TITLE
Update 01-01-2017.owrs

### PR DESCRIPTION
**Pull request by macchi92**
http://docs.poway.org/WebLink/DocView.aspx?dbid=0&id=111387&page=1&cr=1

It says the billing it's bimonthly. Also, I am not sure about how to interpret this 

    service_charge: 5.05
    commodity_charge: 0
    fixed_drought_surcharge: 0.75
    variable_drought_surcharge: 0
    fixed_wastewater_charge: 0
    variable_wastewater_charge: 0
    bill: service_charge+commodity_charge

### CODE REVIEW

**Comment by christophertull** [comment]
Looks like whoever first entered the rates got the service charge mixed up with the commodity charge.

Service charges:
image

Commodity charges:
image

Drought charge almost looks right, but it should actually be a variable "per unit" charge, not a fixed charge:
image

**Comment by patwater** [comment]
Cool have those been added to the underlying file yet @christophertull ?

**Comment by christophertull** [comment]
Doesn't appear so @patwater . Could you please fix the file @macchi92 ?

**Comment by patwater** [comment]
Appears there's two Poway branches. I fixed the other and am deleting this one

**Pull request closed without merging**
