### PR TITLE
Adding Sunny Slope Water Company OWRS file for 05-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
https://static1.squarespace.com/static/51c9af85e4b0ba13e3125d7c/t/58ece74fdb29d6ca05f4609f/1491920720557/2017+Water+Rate+Table.pdf

**Comment by ArashSeif** [comment]
@patwater @christophertull Please Review

**Comment by christophertull** [comment]
@ArashSeif looks like this is 800 CF which is only 8 CCF. Please change then feel free to merge and delete branch

**Comment by ArashSeif** [comment]
@christophertull @patwater Corrected and merged.

**Pull request merged**
