### PR TITLE
Adding Calaveras Public Utilities District OWRS file for 7-1-2016

### PR DESCRIPTION
**Pull request by patwater**
NOT READY TO MERGE (yet)

### CODE REVIEW

**Comment by ArashSeif** [comment]
@christophertull @patwater Please Review.

https://www.cpud.org/files/d1db6b6b9/Schedule+E.pdf

**Comment by christophertull** [comment]
This looks like a very similar situation to the one I just described here: https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/pull/218

**Comment by patwater** [comment]
CC @ArashSeif

**Comment by ArashSeif** [comment]
@christophertull @patwater Please review

**Comment by christophertull** [comment]
@ArashSeif  Looks like the tiers don't depend on meter size like we discussed in the call on Monday?

**Comment by patwater** [comment]
@ArashSeif nudging this back up in your inbox

**Comment by ArashSeif** [comment]
@patwater @christophertull My apologies for the delay. It's fixed now, please review.

**Pull request merged**
