### PR TITLE
Adding Lincoln city of OWRS file for 07-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull please review
http://lincolnca.gov/home/showdocument?id=6133

**Comment by patwater** [comment]
The volumetric charges appear to be broken out by meter size and not pressure zone as specified in the file: http://lincolnca.gov/home/showdocument?id=6133

**Comment by ArashSeif** [comment]
That's correct for all expect single family residential. For SFR, tier breaks are based on their location, "Verdera Village 13-17,19", "Verdera Village 20", and "All Except Verdera Village 13-17,19 & 20".
Would it be better if I change zone numbers to the actual name of the areas?

**Comment by patwater** [comment]
Yes please

**Comment by ArashSeif** [comment]
Done. Ready to merge.

**Pull request merged**
