### PR TITLE
Normalized meter_size values, add some missing colons, remove some duplicate properties.

### PR DESCRIPTION
**Pull request by LindseyKnight**
The bulk of the change is to meter_size values. Additional changes include the following:

Corona City of
	- Add preceding space to `service_charge` and `bill` properties so they are properly indented beneath the consumer class
	
Garden Grove City of 
	- Add comment pound sign to fix YAML parse exception
	- Fix typo
	
Glendale City of
	- Remove extra `service_charge` property
	
Las Virgenes Municipal Water District
Riverside City of
	- Add missing colons after property

### CODE REVIEW

**Comment by christophertull** [comment]
Thanks for your help, and good eye on all the little errors @LindseyKnight! 

I think the |'s are being added by the web tool right now (I forget, what was the reason for adding them via the web tool @vincent-hebble ?) but they are not necessary for RateParser and probably should be replaced with spaces like you have done here Lindsey.

You mention a YAML parse error - does that mean you have been using the [RateParser](https://github.com/California-Data-Collaborative/RateParser)? If so how was the experience? I am always happy to see folks using the software we worked hard to write :)

**Comment by LindseyKnight** [comment]
I was tasked with creating an Excel file with all of the data from this repo, a bit more challenging than I was expecting at first!
I'm using YamlDotNet, a NuGet package to parse the YAML. I did not know of the existence of the RateParser, I'll have to check it out!
I'm happy to send you the program I wrote, or the output, if you're interested.

**Comment by patwater** [comment]
Yes feel free to share your program in this thread and let us know how RateParser deals with these issues. Cheers

**Comment by patwater** [comment]
@LindseyKnight what's the easiest way on your end to share the program you wrote and output?

**Comment by LindseyKnight** [comment]
@patwater I'll add it to my repositories and leave a link here later today. Sorry to keep you waiting!

**Comment by LindseyKnight** [comment]
@patwater  The program is [here](https://github.com/LindseyKnight/Open-Water-Rate-Specification-Tools).

**Comment by patwater** [comment]
@LindseyKnight have you been working with Kevin on the QA/QC? I just received the attached file which Kevin indicated included corrections. I'm trying to backtrack those edits so we can include in the main repo. 

[Copy of UtilityData_2017-12-07 (Wide Clean) v2.xlsx](https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/files/1657144/Copy.of.UtilityData_2017-12-07.Wide.Clean.v2.xlsx)

**Comment by patwater** [comment]
I suspect that is derived from this file ( https://github.com/LindseyKnight/Open-Water-Rate-Specification-Tools/blob/master/ToExcel/Agencies.xlsx ) 

Is there an interim step that more closely aligns with the format of the final "UtilityData_2017-12-07 (Wide Clean) v2.xlsx"

CC @kkostiuk

**Pull request merged**
