### PR TITLE
Adding Indio  City Of OWRS file for 01-01-2014

### PR DESCRIPTION
**Pull request by christophertull**

### CODE REVIEW

**Comment by christophertull** [comment]
Link to rate info online is broken. I have an email out to customer service for info

**Comment by ArashSeif** [comment]
@patwater @christophertull 
2018 rates are added. Couldn't find info online confirming 2014 rates. Please review. 
http://www.indio.org/documents/IWA/RATES%20AND%20SERVICE%20FEES%20%20-%202018.pdf
http://www.indio.org/your_government/water/iwa/forms_n_fees/default.htm

**Comment by christophertull** [comment]
@ArashSeif where did you find info on their budget tier widths (e.g. 100%, 125%, etc)? Couldn't find online

**Comment by ArashSeif** [comment]
Couldn't find anything at first. Just found this WRSAC Presentation from June 2013 and updated the values based on that. Let me know whether it seems right.
http://www.indio.org/civicax/filebank/blobdload.aspx?BlobID=23270
http://www.indio.org/your_government/water/conservation/tiered_rates.htm

**Comment by christophertull** [comment]
Nice! good find. Yeah I think you are about right, except I tweaks the 3rd tier from 150% to 100% 

Kind of annoying that you have to reverse-engineer it from a plot instead of them just saying what the tiers are.

**Pull request merged**
