### PR TITLE
Adding Westminister  City Of OWRS file for 11-09-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by christophertull** [comment]
This is great stuff @ArashSeif, we really appreciate how thorough you are!

**Comment by patwater** [comment]
@christophertull wasn't this the one that @ArashSeif was going to add in the monthly meter service charge?

**Comment by christophertull** [comment]
Whoops, my bad if so! Can be edited directly here: https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/blob/master/full_utility_rates/California/Westminister%20%20City%20Of%20-%203161/11-09-2017.owrs

**Comment by ArashSeif** [comment]
Thank you @christophertull, I'm happy to hear that and I'm glad to be part of this.

**Comment by patwater** [comment]
@ArashSeif could you please confirm if this is the one you mentioned on this mornings call that needed to be tweaked?

**Comment by ArashSeif** [comment]
@patwater Yes this was the one. I've already added the service charge ($8.39) to the meter charges.

**Pull request merged**
