### PR TITLE
Adding Reedley  City Of OWRS file for 08-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull please review 
http://www.reedley.com/departments/administrative/pdfs/Citywide%20Master%20Fee%20Schedule.pdf

**Comment by ArashSeif** [comment]
@christophertull drought rates are given under 4 different stages. How do you want me to edit those into the code?

**Comment by patwater** [comment]
Can you do Reedley in a similar structure to Ukiah? https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/pull/267

**Comment by ArashSeif** [comment]
Stage 1 rates are on file. A comment about existing of other stages is added.

**Pull request merged**
