### PR TITLE
Adding Fortuna  City Of OWRS file for 09-11-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull please review this as I'm not sure about a few things.
- Would like to know your opinion on whether the base charge should also be multiplied by 1.5 for outside city?
- Also please review my adjustments for MFR.
Refer to page 33, section 5a-5d
http://www.friendlyfortuna.com/documentcenter/view/2731

**Comment by ArashSeif** [comment]
Base charge for outside city is now added to the code.

Also, 1.35 was an error, and 2.85 is the correct value.

**Comment by patwater** [comment]
@christophertull good to merge?

**Comment by christophertull** [comment]
@ArashSeif the inside/outside city prices look good! 

Why did you tweak the summer/winter tier starts though? 

>*Summer Usage Charge*
Between May and October each year summer water rates will be in effect for all customers.
The summer rates will provide each customer under the base rate with an additional 200
cubic feet of water each month. 

This sounds to me like the 3ccf should be in winter and the 5ccf in summer, which is how you had it before? Unless I am misinterpreting?

**Comment by ArashSeif** [comment]
@christophertull you are right, my mistake. Just changed it back to 5ccf for summer and 3ccf for winter.

**Comment by patwater** [comment]
@ArashSeif good to merge?

**Pull request merged**
