### PR TITLE
Adding Camarillo  City Of OWRS file for 01-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull Please review

**Comment by ArashSeif** [comment]
http://www.cityofcamarillo.org/Water/Rate%20Increase%202018/Prop%20218%20notice%20Water%20Rates%20Public%20Hearing%2011-01-17%20FINAL.pdf

**Comment by christophertull** [comment]
@ArashSeif in situations where is it very easy like this, could you please add in the other customer classes listed in the Rate sheet? At least the major ones: RESIDENTIAL_SINGLE, RESIDENTIAL_MULTI, COMMERCIAL

I know we said to prioritize single-family because often it is hard to find info on non-SFR rates, but always nice to have the other customer classes also.

Thanks!

**Comment by patwater** [comment]
CC @ArashSeif

**Comment by ArashSeif** [comment]
@christophertull @patwater 
Other costumer classes are added. Please review.

**Comment by christophertull** [comment]
Thanks!

**Pull request merged**
