### PR TITLE
Adding Delano  City Of OWRS file for 07-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull your thoughts on how to input the unmetered section? 
http://www.cityofdelano.org/documentcenter/view/3085

**Comment by patwater** [comment]
Hmmm I know Sacramento has unmetered accounts though that does not seem to be reflected in the Sac OWRS file. One thought would be to ignore the unmetered accounts or could setup an "UNMETERED" customer class and specify the unmetered rates there. 

@christophertull thoughts?

https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/blob/master/full_utility_rates/California/Sacramento%20%20City%20Of%20-%202479/07-01-2017.owrs

-

**Comment by christophertull** [comment]
Yeah `UNMETERED` class would be good. Or maybe `RESIDENTIAL_SINGLE_UNMETERED` and `RESIDENTIAL_MULTI_UNMETERED` if we really wanna get picky. Not sure we will be analyzing those classes anyways so might be a moot question, but good to preserve the info somehow I suppose.

**Comment by ArashSeif** [comment]
@patwater unmetered rates are added

**Pull request merged**
