### PR TITLE
Adding CALAVERAS COUNTY WATER DISTRICT OWRS file for 09-01-2017

### PR DESCRIPTION
**Pull request by ArashSeif**

### CODE REVIEW

**Comment by ArashSeif** [comment]
@patwater @christophertull Please Review.

http://ccwd.org/wp-content/uploads/2013/12/2013-2017-CCWD-Wastewater-and-Water-Rate-Sheet-1.pdf

**Comment by patwater** [comment]
Thanks! Note we also have another PR open for 2016: https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/pull/75

**Comment by christophertull** [comment]
Two notes:

1. It looks like their pricing doesn't actually start at 0 CCF, but rather the first few CCF are included in the service charge. e.g.

```yaml
 tier_starts_commodity:
  - 0
  - 10
  - 60
  - 120
tier_prices_commodity:
  - 0
  - 1.25
  - 1.56
  - 2
```

2. Looks like their tiers also depend upon meter size. If you re-enter the information using the survey form you can specify that their tiers "depend on" meter size to capture this properly.

**Comment by patwater** [comment]
CC @ArashSeif please let us know if you have any questions

**Comment by ArashSeif** [comment]
@christophertull @patwater file is now updated and corrected. Please review and let me know if there's anything else.

**Comment by christophertull** [comment]
looks good!

**Pull request merged**
